schemaVersion: "2.0.0"

commandTests:
  - name: "current user"
    command: "whoami"
    expectedOutput: ["default"]

  - name: "npm installation"
    command: "npm"
    args: ["help"]
    expectedOutput: ["Usage: npm <command>.*"]

fileExistenceTests:
  - name: 'package.json'
    path: '/opt/app-root/src/app/package.json'
    shouldExist: true